version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:latest
    container_name: climate-risk-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=climate_risk_intelligence
    restart: unless-stopped
    networks:
      - climate-risk-network

  # FastAPI backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: climate-risk-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - ENVIRONMENT=production
      - DEBUG=False
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - climate-risk-network

  # React frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: climate-risk-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - climate-risk-network

networks:
  climate-risk-network:
    driver: bridge

volumes:
  mongodb_data: